name: Cypress Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          # Adicione a chave do seu projeto do Cypress Cloud se for usar
        # env:
          # CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Upload Reports
        # Carrega os relatórios apenas se algum teste falhar
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports

      - name: Upload Screenshots and Videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-media
          path: |
            cypress/screenshots
            cypress/videos
