name: PGATS Aut web

on: 
  workflow_dispatch: 
jobs: 
  e2e-tests:

   runs-on: ubuntu-latest

   steps:
     # clone do projeto para a máquina
    - uses: actions/checkout@v4
    - name: Node version
      run: node --version

    - name: Instalando dependências
      run: npm install

    - name: Executando os testes
      run: npx cypress run

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
          name: relatorios
          path: |
            cypress/reports
            cypress/screenshorts
            cypress/videos 
            
        
     
